service: rimac-tech-challenge
# app and org for use with dashboard.serverless.com
app: rimac-tech-challenge
org: luis199230

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

  cfnRole: arn:aws:iam::975937631079:role/devops

  # Environment variables
  environment:
    SCHEMA_TABLE: ${self:service}-${self:provider.stage}-schema
    API_URL: https://swapi.py4e.com

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - schemaTable
          - Arn

functions:
  listSchemas:
    handler: app/app.listSchemas
    description: Collect the fields of third API StarWars for translate key in others endpoints.
    events:
      - http:
          path: schemas
          method: post

  listCharacters:
    handler: app/app.listCharacters
    description: Show list of characters.
    events:
      - http:
          path: people
          method: get

resources:
  - ${file(resources/dynamo.yml)}